train-adversary-all-real:
  data-dir: D:\Programs\VS repos\Fool the model\fool-the-model\data
  classifier-path: D:/Programs/VS repos/Fool the model/fool-the-model/best_dt.pkl
  save-path: D:\Programs\VS repos\Fool the model\fool-the-model\results\adversarial\good_perception\e01_allreal_adversary.pth
  img-size: 128
  batch-size: 12
  lr: 0.0002
  epochs: 100
  lper: 0.1 # Deactivate
  seed: 42
  dataset-fraction: 0.01
  epsilon: 0.01
  
